CREATE TABLE IF NOT EXISTS TM_STD_RUNTIME_CONFIG_MAIN (
  runtime_config_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  config_group_cd VARCHAR(80) NOT NULL,
  config_key VARCHAR(120) NOT NULL,
  config_name VARCHAR(160) NOT NULL,
  value_type_cd VARCHAR(20) NOT NULL DEFAULT 'STRING',
  config_value VARCHAR(2000) NOT NULL,
  config_desc VARCHAR(1000) NULL,
  sort_no INT NOT NULL DEFAULT 100,
  editable_yn TINYINT(1) NOT NULL DEFAULT 1,
  use_yn TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (runtime_config_id),
  UNIQUE KEY uq_tm_std_runtime_config_main_group_key (config_group_cd, config_key),
  KEY idx_tm_std_runtime_config_main_group_sort (config_group_cd, sort_no),
  CONSTRAINT fk_tm_std_runtime_config_main_group
    FOREIGN KEY (config_group_cd) REFERENCES TM_STD_CODE_MAIN(code_group_cd)
);

INSERT INTO TM_STD_CODE_MAIN(code_group_cd, code_group_nm, code_group_desc, use_yn)
VALUES
  ('ADVISOR_RULE', '포트폴리오 규칙 기준정보', '리밸런싱/리스크 진단 조건값 기준정보', 1),
  ('ADVISOR_MESSAGE', '포트폴리오 문구 기준정보', '진단/추천 멘트 템플릿 기준정보', 1),
  ('SIMULATION_MESSAGE', '시뮬레이터 문구 기준정보', '기간 수익 시뮬레이터 멘트 기준정보', 1)
ON DUPLICATE KEY UPDATE
  code_group_nm = VALUES(code_group_nm),
  code_group_desc = VALUES(code_group_desc),
  use_yn = VALUES(use_yn),
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO TM_STD_RUNTIME_CONFIG_MAIN(
  config_group_cd, config_key, config_name, value_type_cd, config_value, config_desc, sort_no, editable_yn, use_yn
)
VALUES
  ('ADVISOR_RULE', 'analytics.trading_days_per_year', '연 환산 거래일수', 'NUMBER', '252', '수익률/변동성 연환산에 사용할 거래일수', 10, 1, 1),
  ('ADVISOR_RULE', 'analytics.risk_free_rate_pct', '무위험 수익률(%)', 'NUMBER', '3.0', '샤프지수 계산에 사용하는 기준 무위험 수익률', 20, 1, 1),
  ('ADVISOR_RULE', 'analytics.min_annual_volatility_pct', '최소 연환산 변동성(%)', 'NUMBER', '9.0', '데이터 부족 시 적용되는 최소 변동성 하한', 30, 1, 1),
  ('ADVISOR_RULE', 'analytics.min_stddev_from_pnl_pct', '손익기반 표준편차 최소치(%)', 'NUMBER', '8.0', '포지션 PnL 기반 변동성 추정 최소치', 40, 1, 1),
  ('ADVISOR_RULE', 'analytics.min_drawdown_fallback_pct', '최대낙폭 기본값(%)', 'NUMBER', '4.0', '시계열 부족 시 최대낙폭 기본값', 50, 1, 1),
  ('ADVISOR_RULE', 'analytics.drawdown_concentration_factor', '집중도-낙폭 계수', 'NUMBER', '0.25', '시계열 부족 시 집중도 기반 낙폭 보정 계수', 60, 1, 1),
  ('ADVISOR_RULE', 'rebal.min_weight_low_tier', '저위험 최소 비중(%)', 'NUMBER', '8.0', '리스크 1~2 티어 최소 목표 비중', 100, 1, 1),
  ('ADVISOR_RULE', 'rebal.max_weight_low_tier', '저위험 최대 비중(%)', 'NUMBER', '24.0', '리스크 1~3 티어 최대 목표 비중', 110, 1, 1),
  ('ADVISOR_RULE', 'rebal.max_weight_mid_tier', '중위험 최대 비중(%)', 'NUMBER', '30.0', '리스크 4 티어 최대 목표 비중', 120, 1, 1),
  ('ADVISOR_RULE', 'rebal.max_weight_high_tier', '고위험 최대 비중(%)', 'NUMBER', '35.0', '리스크 5 이상 티어 최대 목표 비중', 130, 1, 1),
  ('ADVISOR_RULE', 'rebal.gap_threshold_low_tier', '저위험 편차 임계값(%)', 'NUMBER', '2.0', '리스크 1~2 티어 리밸런싱 편차 임계치', 140, 1, 1),
  ('ADVISOR_RULE', 'rebal.gap_threshold_mid_tier', '중위험 편차 임계값(%)', 'NUMBER', '2.5', '리스크 3~4 티어 리밸런싱 편차 임계치', 150, 1, 1),
  ('ADVISOR_RULE', 'rebal.gap_threshold_high_tier', '고위험 편차 임계값(%)', 'NUMBER', '3.0', '리스크 5 이상 티어 리밸런싱 편차 임계치', 160, 1, 1),
  ('ADVISOR_RULE', 'rebal.max_action_count', '리밸런싱 최대 추천 수', 'NUMBER', '6', '리밸런싱 추천 최대 표시 건수', 170, 1, 1),
  ('ADVISOR_RULE', 'etf.max_recommendation_count', 'ETF 최대 추천 수', 'NUMBER', '3', 'ETF 추천 최대 표시 건수', 180, 1, 1),
  ('ADVISOR_RULE', 'stability.annual_volatility_max_pct', '안정판단 변동성 상한(%)', 'NUMBER', '18.0', '안정판단 시 연환산 변동성 상한', 200, 1, 1),
  ('ADVISOR_RULE', 'stability.max_drawdown_max_pct', '안정판단 낙폭 상한(%)', 'NUMBER', '10.0', '안정판단 시 최대낙폭 상한', 210, 1, 1),
  ('ADVISOR_RULE', 'stability.max_concentration_max_pct', '안정판단 집중도 상한(%)', 'NUMBER', '35.0', '안정판단 시 최대 종목 비중 상한', 220, 1, 1),
  ('ADVISOR_RULE', 'stability.min_diversification_score', '안정판단 분산점수 하한', 'NUMBER', '60.0', '안정판단 시 분산점수 최소값', 230, 1, 1),
  ('ADVISOR_RULE', 'stability.max_gap_pct', '안정판단 리밸런싱 편차 상한(%)', 'NUMBER', '4.0', '안정판단 시 권장 편차 상한', 240, 1, 1),
  ('ADVISOR_RULE', 'risk.high.annual_volatility_min_pct', '리스크높음 변동성 하한(%)', 'NUMBER', '35.0', '리스크높음 판정 변동성 하한', 250, 1, 1),
  ('ADVISOR_RULE', 'risk.high.max_drawdown_min_pct', '리스크높음 낙폭 하한(%)', 'NUMBER', '18.0', '리스크높음 판정 낙폭 하한', 260, 1, 1),
  ('ADVISOR_RULE', 'risk.high.concentration_min_pct', '리스크높음 집중도 하한(%)', 'NUMBER', '45.0', '리스크높음 판정 집중도 하한', 270, 1, 1),
  ('ADVISOR_RULE', 'risk.medium.annual_volatility_min_pct', '리스크보통 변동성 하한(%)', 'NUMBER', '20.0', '리스크보통 판정 변동성 하한', 280, 1, 1),
  ('ADVISOR_RULE', 'risk.medium.max_drawdown_min_pct', '리스크보통 낙폭 하한(%)', 'NUMBER', '10.0', '리스크보통 판정 낙폭 하한', 290, 1, 1),
  ('ADVISOR_RULE', 'risk.medium.concentration_min_pct', '리스크보통 집중도 하한(%)', 'NUMBER', '30.0', '리스크보통 판정 집중도 하한', 300, 1, 1),
  ('ADVISOR_RULE', 'insight.low_diversification_threshold', '분산점수 낮음 기준', 'NUMBER', '55.0', '분산 점수 기준(이 값 미만일 때 분산 보강 메시지 적용)', 310, 1, 1),
  ('ADVISOR_MESSAGE', 'advice.empty.metrics_risk_level', '빈 데이터 위험 레벨', 'STRING', '데이터가 아직 부족해요', '보유 데이터 부족 시 기본 위험 레벨 문구', 10, 1, 1),
  ('ADVISOR_MESSAGE', 'advice.empty.headline', '빈 데이터 헤드라인', 'STRING', '포트폴리오 데이터가 더 필요해요', '보유 데이터 부족 시 헤드라인', 20, 1, 1),
  ('ADVISOR_MESSAGE', 'advice.empty.summary', '빈 데이터 요약', 'STRING', '보유 자산 데이터가 아직 충분하지 않아서 정교한 진단이 어려워요.', '보유 데이터 부족 시 요약 문구', 30, 1, 1),
  ('ADVISOR_MESSAGE', 'advice.empty.key_point_1', '빈 데이터 키포인트', 'STRING', '거래를 등록하면 샤프지수, 리스크, ETF 제안을 바로 보여드릴게요.', '보유 데이터 부족 시 키포인트 문구', 40, 1, 1),
  ('ADVISOR_MESSAGE', 'advice.empty.caution_1', '빈 데이터 주의문구', 'STRING', '데이터가 적은 구간의 추정값은 오차가 커질 수 있어요.', '보유 데이터 부족 시 주의문구', 50, 1, 1),
  ('ADVISOR_MESSAGE', 'insight.headline.stable', '안정 구간 헤드라인', 'STRING', '지금 포트폴리오는 비교적 안정 구간이에요', '안정 구간 진단 헤드라인', 100, 1, 1),
  ('ADVISOR_MESSAGE', 'insight.headline.adjust', '조정 필요 헤드라인', 'STRING', '리밸런싱/분산 조정이 필요한 구간이에요', '조정 필요 진단 헤드라인', 110, 1, 1),
  ('ADVISOR_MESSAGE', 'insight.summary.stable.template', '안정 구간 요약 템플릿', 'STRING', '샤프 %.2f, 연환산 변동성 %.2f%%, 최대낙폭 %.2f%%, 최대 비중 %.2f%% 기준으로는 급격한 구조 변경보다 운영 전략 점검이 더 좋아요', '안정 구간 요약 템플릿', 120, 1, 1),
  ('ADVISOR_MESSAGE', 'insight.summary.adjust.template', '조정 필요 요약 템플릿', 'STRING', '샤프 %.2f, 연환산 변동성 %.2f%%, 최대낙폭 %.2f%%, 최대 비중 %.2f%% 기준으로 비중 조정 우선순위가 있어요', '조정 필요 요약 템플릿', 130, 1, 1),
  ('ADVISOR_MESSAGE', 'insight.keypoint.stable.default_1', '안정 구간 기본 키포인트', 'STRING', '지금은 구조를 크게 바꾸기보다 과도한 매매를 줄이고 운영 전략을 유지하는 편이 좋아요.', '안정 구간 키포인트 기본값', 140, 1, 1),
  ('ADVISOR_MESSAGE', 'insight.keypoint.adjust.profile.template', '성향 반영 키포인트 템플릿', 'STRING', '현재 성향 %s(%d단계)을 기준으로 추천 우선순위를 개인화했어요.', '성향 반영 키포인트 템플릿', 150, 1, 1),
  ('ADVISOR_MESSAGE', 'insight.keypoint.adjust.no_action', '조정 없음 키포인트', 'STRING', '즉시 체결이 필요한 조정은 없지만 정기 리밸런싱 점검은 계속 필요해요.', '조정 없음 키포인트', 160, 1, 1),
  ('ADVISOR_MESSAGE', 'insight.keypoint.adjust.top_action.template', '최우선 리밸런싱 키포인트 템플릿', 'STRING', '우선 조정은 %s %s이고 권장 금액은 약 %,d원이에요.', '최우선 리밸런싱 키포인트 템플릿', 170, 1, 1),
  ('ADVISOR_MESSAGE', 'insight.keypoint.adjust.top_etf.template', '최우선 ETF 키포인트 템플릿', 'STRING', 'ETF 대안은 %s %s이고, 적합도 %d점 기준 권장 비중은 %.1f%%예요.', '최우선 ETF 키포인트 템플릿', 180, 1, 1),
  ('ADVISOR_MESSAGE', 'insight.keypoint.adjust.low_diversification', '낮은 분산 점수 키포인트', 'STRING', '분산 점수가 낮아서 섹터/시장 분산 비중을 더 늘리는 쪽이 좋아요.', '낮은 분산 점수 안내 문구', 190, 1, 1),
  ('ADVISOR_MESSAGE', 'insight.keypoint.adjust.high_diversification', '양호한 분산 점수 키포인트', 'STRING', '분산은 비교적 유지되고 있으니 비중 조정은 분할 체결로 천천히 가는 편이 좋아요.', '양호한 분산 점수 안내 문구', 200, 1, 1),
  ('ADVISOR_MESSAGE', 'insight.caution.base', '공통 주의문구', 'STRING', '이 진단은 규칙 기반 보조지표이고, 최종 투자 판단은 사용자에게 있어요.', '공통 주의문구', 210, 1, 1),
  ('ADVISOR_MESSAGE', 'insight.caution.stable', '안정 구간 주의문구', 'STRING', '운영 임계치는 변동성 20%, 최대낙폭 12%, 최대 비중 40% 수준으로 두는 걸 권장해요.', '안정 구간 주의문구', 220, 1, 1),
  ('ADVISOR_MESSAGE', 'insight.caution.high_drawdown', '낙폭 구간 주의문구', 'STRING', '최대낙폭이 큰 구간이라면 현금 비중이나 방어자산 비중을 먼저 점검해 주세요.', '낙폭 구간 주의문구', 230, 1, 1),
  ('ADVISOR_MESSAGE', 'insight.caution.default', '일반 구간 주의문구', 'STRING', '변동성 확대 가능성을 고려해서 일괄 체결보다는 분할 리밸런싱이 더 안전해요.', '일반 구간 주의문구', 240, 1, 1),
  ('ADVISOR_MESSAGE', 'stable.strategy.monthly_check', '안정전략 월간점검 문구', 'STRING', '운영전략 1) 월 1회 점검하고 허용오차(±3%)를 벗어날 때만 리밸런싱해요.', '안정 구간 운영전략 기본 문구', 250, 1, 1),
  ('ADVISOR_MESSAGE', 'stable.strategy.diversification.template', '안정전략 분산점수 템플릿', 'STRING', '운영전략 2) 분산 점수 %.1f점을 유지 목표로 두고, 신규 자금으로 비중을 보정해요.', '안정전략 분산점수 템플릿', 260, 1, 1),
  ('ADVISOR_MESSAGE', 'stable.strategy.etf.template', '안정전략 ETF 템플릿', 'STRING', '운영전략 3) %s(%s)는 즉시 교체보다 신규 매수분에서 점진 반영하는 편이 좋아요.', '안정전략 ETF 템플릿', 270, 1, 1),
  ('ADVISOR_MESSAGE', 'rebal.reason.buy.template', '리밸런싱 매수 사유 템플릿', 'STRING', '현재 비중 %.1f%%가 목표 %.1f%%보다 낮아서 분할 매수가 좋아요', '리밸런싱 매수 사유 템플릿', 280, 1, 1),
  ('ADVISOR_MESSAGE', 'rebal.reason.sell.template', '리밸런싱 매도 사유 템플릿', 'STRING', '현재 비중 %.1f%%가 목표 %.1f%%를 넘어서 일부 축소가 좋아요', '리밸런싱 매도 사유 템플릿', 290, 1, 1),
  ('ADVISOR_MESSAGE', 'rebal.reason.profile_suffix.template', '리밸런싱 성향 접미 템플릿', 'STRING', ' (%s 성향 반영)', '리밸런싱 사유에 붙는 성향 반영 접미문구', 300, 1, 1),
  ('ADVISOR_MESSAGE', 'etf.reason.template', 'ETF 추천 사유 템플릿', 'STRING', '%s 목적이고, 총보수는 %.4f%%예요', 'ETF 추천 사유 템플릿', 310, 1, 1),
  ('SIMULATION_MESSAGE', 'simulation.note.1', '시뮬레이션 안내 문구1', 'STRING', '실제 체결가와 세금/수수료를 반영하면 결과가 달라질 수 있어요.', '시뮬레이션 안내 문구', 10, 1, 1),
  ('SIMULATION_MESSAGE', 'simulation.note.2', '시뮬레이션 안내 문구2', 'STRING', '조회 구간은 시작가(기준일)와 종료가(평가일) 기준이라 장중 체결가와 차이가 날 수 있어요.', '시뮬레이션 안내 문구', 20, 1, 1),
  ('SIMULATION_MESSAGE', 'simulation.note.short_period', '시뮬레이션 단기 문구', 'STRING', '조회 기간이 90일 미만이면 연환산 수익률은 참고 지표로 봐 주세요.', '단기 조회 구간 안내 문구', 30, 1, 1),
  ('SIMULATION_MESSAGE', 'simulation.note.long_period', '시뮬레이션 장기 문구', 'STRING', '연환산 수익률은 장기 비교용으로 보고, 단기 성과는 누적 수익률과 함께 확인해 주세요.', '장기 조회 구간 안내 문구', 40, 1, 1),
  ('SIMULATION_MESSAGE', 'simulation.note.3', '시뮬레이션 안내 문구3', 'STRING', '종목 기여도는 현재 보유수량 기준 추정값이니 리밸런싱 계획과 같이 해석해 주세요.', '시뮬레이션 안내 문구', 50, 1, 1),
  ('SIMULATION_MESSAGE', 'simulation.empty.note.1', '시뮬레이션 빈 데이터 문구1', 'STRING', '선택한 기간에는 시뮬레이션에 필요한 가격 데이터가 부족해요.', '시뮬레이션 데이터 부족 문구', 60, 1, 1),
  ('SIMULATION_MESSAGE', 'simulation.empty.note.2', '시뮬레이션 빈 데이터 문구2', 'STRING', '시작일을 최근으로 조정하거나 시세 배치 상태를 확인해 주세요.', '시뮬레이션 데이터 부족 문구', 70, 1, 1),
  ('SIMULATION_MESSAGE', 'simulation.error.invalid_date_range', '시작/종료일 검증 에러', 'STRING', '시작일은 기준일보다 이후일 수 없어요.', '시뮬레이션 조회 기간 유효성 검증 실패 메시지', 80, 1, 1),
  ('SIMULATION_MESSAGE', 'transaction.error.account_verify', '계좌 검증 실패 에러', 'STRING', '사용자 계좌 검증에 실패했어요.', '거래 등록 시 계좌 검증 실패 메시지', 90, 1, 1),
  ('SIMULATION_MESSAGE', 'alert.error.at_least_one_enabled', '알림레벨 검증 에러', 'STRING', '최소 1개 이상의 알림 레벨을 켜야 해요.', '알림 레벨 전체 OFF 방지 메시지', 100, 1, 1)
ON DUPLICATE KEY UPDATE
  config_name = VALUES(config_name),
  value_type_cd = VALUES(value_type_cd),
  config_value = VALUES(config_value),
  config_desc = VALUES(config_desc),
  sort_no = VALUES(sort_no),
  editable_yn = VALUES(editable_yn),
  use_yn = VALUES(use_yn),
  updated_at = CURRENT_TIMESTAMP;
